# Generated by Django 4.2.16 on 2024-09-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sanctuary_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanctuary',
            name='dog_sanctuary',
        ),
        migrations.AddField(
            model_name='post',
            name='sanctuary',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='blog.sanctuary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanctuary',
            name='sanct_name',
            field=models.TextField(default='data'),
            preserve_default=False,
        ),
    ]
