# Generated by Django 4.2.16 on 2024-09-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sanctuary_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sanctuary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='blog.sanctuary'),
            preserve_default=False,
        ),
    ]
